### ISSUE TITLE
⚠️ Know the risks before use ⚠️

### ISSUE THREAD

**Issue by tornikeo** [amitness/colab-tunnel#2]
Using this tool [breaks colab terms of service](https://research.google.com/colaboratory/faq.html#limitations-and-restrictions). Specifically: 

![image](https://user-images.githubusercontent.com/56438982/232887347-616d4be8-f580-4840-b95c-463138a2c85d.png)

Keep in mind, **I support these kinds of tools** (I used [ColabSSH](https://github.com/WassimBenzarti/colab-ssh) myself at some point) - but this one will likely cause people to get banned out of the blue unless google decides to amend collab TOS.

Also, @amitness , it'd be nice to have this notice on the readme, so that we don't get people banned from colab.

**Comment by amitness** [comment]
@tornikeo Thanks, that's a good point. I've added a notice to the README.
<img width="971" alt="image" src="https://user-images.githubusercontent.com/8587189/233203375-c81bd929-948c-471b-83b6-6e4a5a3273a7.png">


Regarding banning, usually I've seen that Google Colab bans the library code rather than the user. For example, [colabcode](https://github.com/abhishekkrthakur/colabcode) got banned. So, when running colabcode, I've noticed getting a popup alerting me to not run it. Ofcourse, if you pip install it directly from github or a fork, it bypasses their detection algorithm. Seems like they're simply matching the cell code to some pre-defined blacklist.
